### ISSUE TITLE
nodepress 安装运行问题

### ISSUE THREAD

**Issue by huming0618** [linejoy/nodepress#1]
- windows安装出错
- 运行npm run start:dev
```
/tmp/nodepress/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/modules/sitemap/sitemap.module.ts(9,33): error TS2307: Cannot find module 'n          estjs-typegoose'.

    at createTSError (/tmp/nodepress/
```

在window上运行 npmi 报错
```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\admin\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\workspace\nodepress\node_modules\hiredis
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN typegoose@5.4.1 requires a peer of mongoose@5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\simple-netease-cloud-music\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hiredis@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2019-01-23T02_48_24_195Z-debug.log
```

**Comment by zhangwen9229** [comment]
看上去是mongodb问题？

**Comment by huming0618** [comment]
windows 环境变量设置问题  使用cross-env
https://github.com/PanJiaChen/vue-element-admin/issues/21

**Comment by huming0618** [comment]
针对window 运行 npm i遇到的node-gyp问题 需要设置python 变量
`npm config set python C:\python27\python.exe`

**Comment by huming0618** [comment]
https://github.com/linejoy/nodepress/commit/60a0a8243117021d59aec19e67ede58b2e3bdc4b

**Comment by huming0618** [comment]
https://github.com/linejoy/nodepress/commit/60a0a8243117021d59aec19e67ede58b2e3bdc4b
